### ISSUE TITLE
Can't Patch x86 EDGE

### ISSUE THREAD

**Issue by darkalexis1990** [Blaukovitch/EDGE.Patcher#1]
@Blaukovitch 

cant patch the x64 im getting the follow errors please help 
![image](https://github.com/user-attachments/assets/1066b82c-d438-41c2-b4ac-3f8fabbad1cc)

![image](https://github.com/user-attachments/assets/de564032-d9c7-4cd6-8aff-6796181fbe4c)

![image](https://github.com/user-attachments/assets/cb419c3c-57b4-4980-b8af-01ad6e7e2ea6)

**Comment by darkalexis1990** [comment]
@Blaukovitch anyway to ask the author of the patch? i cant ask in the forum -you know what forum- because it does not let me to make account there.

**Comment by Blaukovitch** [comment]
@darkalexis1990, i see, that file is not accessible at you `/tmp/Application` folder (**ACCESS IS DENIED**) - check you folder accessibility (from Admin account).

**Comment by darkalexis1990** [comment]
@Blaukovitch  what do you mean by this ? - > Windows 7 machine. Copy API-MS libs (x64/x86) in to ROOT and VER directories;

**Comment by darkalexis1990** [comment]
@Blaukovitch any ideas?

**Comment by darkalexis1990** [comment]
@Blaukovitch  this is as far as i get with the x64:
i do all the steps and i reach the first error:
![edgex64](https://github.com/user-attachments/assets/99c411d7-77b8-40e5-9b2c-5440c5137219)

then i copy that dll and i get this error 
![edgex64-2](https://github.com/user-attachments/assets/8ff01b9f-2609-4b99-affd-f324e6ea5699)
 
dont know what else to do,by the way the x64 125 version from the crack lab pa site that only works i cant reach the site it does not let me to complete the registration it nevers sends the confirmation mail.

now for the x86 version all the steps are completed success but when i doule click the edge.exe it does not open anything even with the no sanbox commmand. in the task manager it shows the procedure.

cam you kindly when you have the time to try to patch by yourself to see what im doing wrong? thanks!.

**Comment by darkalexis1990** [comment]
@Stepman123 , @natsui-river have you tried to patch with success ?

**Comment by darkalexis1990** [comment]
@Blaukovitch  after discusiion on the MDL forum someone had the idea to use the pached api dll's from the edge 125 windows 7 repo that is already patched and IT WORKED. that guy also tested 126 and also worked.the thing is that with the Edge Stable 127.0.2651.74 the patched does not work anymore, cause the API dllls needs again patching. can you please patch/update  your api dlls so we can test with 127? thanks youre the best!!! looking for news from you.

**Comment by natsui-river** [comment]
Hello, I copied some files from GOOGLE_CHROME_WINDOWS_7_CRACK to the Edge directory because after I applied the patch I noticed that kernel64.dll was missing.

**Comment by Blaukovitch** [comment]
> Edge directory because after I applied the patch I noticed that kernel64.dll was missing.

Hi!
EDGE is needed own KERNEL32.DLL.


> Edge Stable 127.0.2651.74 the patched does not work anymore

Some errors?

**Comment by darkalexis1990** [comment]
@Blaukovitch

 first of all i dont have access on https://cracklab.team/index.php?threads/1037/page-8#post-14319
i made an account but it does not send the mail activation so i cant activate the account.

second ,im trying to patch the X86 EDGE because i need that version,cause i have an old machine that only works with 32bit OS so i need edge x86 there.i dont have 109 installed on my win7machine! my machine is full updated!

so i took all the API-MS from your latest chrome x86 release -> 127.0.6533.73_x86_Windows7
.7z
https://mega.nz/file/DcQAmJ5Z#QQJG_waFkvZhlTBcCNtyhtykULjN_R-4e0bdSCgYyqM

and i put them on the API-MS/X86 on the edge patcher . i did the same for the x64 ( i download the 127.0.6533.73_x64_Windows7 and i took also from there all the api-ms files )

im using the command -> 
![image](https://github.com/user-attachments/assets/e83463f3-3525-4d02-aa43-82f77053c205)

i always run cmd with admin rights!

the procedure completes without errors (when i copy the application folder from win11 to 7 i always edit the folder and give permissions uncheck read only etc)



im trying to run and i get this error:
![image](https://github.com/user-attachments/assets/7450f56d-a1ad-4d75-85df-5f4ef613a64f)

then i delete the x64 folder from the API-MS in the edge patcher. i copy again a fresh application folder from my win11

i do again the steps and this is i get ->

![image](https://github.com/user-attachments/assets/04ace1b4-4eb6-4a49-b55a-ab915da39f8d)

maybe it needs the kerner32 youre saying ?

and where i can find this? can you provide it me?

please help me @Blaukovitch

**Comment by Blaukovitch** [comment]
> maybe it needs the KERNEL32.DLL. youre saying that there- > https://github.com/Blaukovitch/EDGE.Patcher/issues/1#issuecomment-2264661027
> and where i can find this? can you provide it me?

@darkalexis1990, i thinks that after Google adds new anti-windows7 tricks, need more research.

**Comment by darkalexis1990** [comment]
@Blaukovitch if you find anything from the research tell me thanks

**Comment by darkalexis1990** [comment]
@Blaukovitch i told you so many times that here youre watched by the companies thats why the new anti 7 tricks/ thats why i told you to come on the forum but you keep avoiding me anyway...

**Comment by veso266** [comment]
@darkalexis1990 I don't think MDL is safe place eather

Look what happened with VxKeX: https://msfn.org/board/topic/186333-vxkex-extended-kernel-project-dissapeared/page/6/

The project disappeared from github (also the user, and it was not DMCA), and the user was mysteriously banned on MDL (nobody knows why)

**Comment by Blaukovitch** [comment]
original copy:
https://github.com/Blaukovitch/VxKex

**Comment by veso266** [comment]
@Blaukovitch Thats great
Do u maybe also have his NotepadEx project: https://github.com/vxiiduu/NotepadEx

A big problem I see with all this projects its, that instead of having to focus to make something good in ur free time
You have to deal with morons, that remove ur projects because they don't like that they exist

If a project is realy popular like VxKex was, its at risk for being shutdown, but a lot of people work on it, which means it progresses

But if a project is not popular, it probably won't get shutdown but is dependend on one or 2 persons working on it, which means that it can get stail rather quickly and its never developed any further

So sometimes I realy don't know what to wish for

I realy hope people will pick up VxKex again, because its the best windows extension we got (I mean if M$ was smart they would develop this themself for money (better then any extended update support they used to offer) and charge corporations that don't want to change :smile: ) but we will see, I guess VxKex needs to find a good place to exist on without worying about being shutdown

**Comment by darkalexis1990** [comment]
> @darkalexis1990, sorry! I have a lot of work to do on my main projects, so I can't afford to develop Chrome Windows 7 and everything related to it separately right now. I've started to notice that the HUGE memory problem is increasing from version to version and needs to be addressed, but I'm running out of time. I think that until the project gets a large number of stars again, it will exist for quite a long time (probably). I guess that Google and Microsoft are extremely unhappy that this project exists in principle, as it perfectly demonstrates the lack of need to switch to new operating systems from Microsoft because the developers can not offer something radically new even a few years after the termination of support for Windows 7 - in fact, nothing fundamentally rules in the browser code, but only formally removed a few conditions "if".
> 
> @veso266, I still have **VkHex** sources, but not the most current version. I can post it for now.

ok man thanks for your work.

**Comment by darkalexis1990** [comment]
> @darkalexis1990 I don't think MDL is safe place eather
> 
> Look what happened with VxKeX: https://msfn.org/board/topic/186333-vxkex-extended-kernel-project-dissapeared/page/6/
> 
> The project disappeared from github (also the user, and it was not DMCA), and the user was mysteriously banned on MDL (nobody knows why)

you think complety wrong. MDL is much safier.also it was a first level protection if you want:you can make your post seen if only you have aaccount there.
